target 'MOBAdvertising_iOS' do
  platform :ios, '13.0'
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK', '13.6.0'
  pod 'GoogleUserMessagingPlatform', '3.1.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
